version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: coin_config
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: coin_config
    ports:
      - "33060:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: {}