/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: mingw64"
#define DATE "built on: Fri Aug 15 02:31:07 2025 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','x','8','6','_','6','4',
    '-','w','6','4','-','m','i','n','g','w','3','2','-','g','c','c',
    ' ','-','m','6','4',' ','-','W','a','l','l',' ','-','O','3',' ',
    '-','D','L','_','E','N','D','I','A','N',' ','-','D','O','P','E',
    'N','S','S','L','_','P','I','C',' ','-','D','U','N','I','C','O',
    'D','E',' ','-','D','_','U','N','I','C','O','D','E',' ','-','D',
    'W','I','N','3','2','_','L','E','A','N','_','A','N','D','_','M',
    'E','A','N',' ','-','D','_','M','T',' ','-','D','O','P','E','N',
    'S','S','L','_','B','U','I','L','D','I','N','G','_','O','P','E',
    'N','S','S','L',' ','-','D','N','D','E','B','U','G','\0'
};
